services:
  app:
    build:
      context: .
      network: host
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/hanaloop.db
      SEED: "true"           # 최초 실행 시 시드 데이터 삽입. 이미 데이터가 있으면 "false"로 변경
    container_name: hanaloop
    volumes:
      - db_data:/app/data    # SQLite DB 영속화
    restart: unless-stopped
    networks:
      # - default
      # nginx-proxy-manager와 함께 쓰면 주석 해제
      - nginx-proxy-manager_default

volumes:
  db_data:

networks:
  # default:
  #   name: app_net
  # nginx-proxy-manager와 연동 시 외부 네트워크 추가 후 위 services.web.networks 에 연결
  nginx-proxy-manager_default:
    external: true